# Generated by Django 3.2.5 on 2021-07-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='objects_id',
            new_name='object_id',
        ),
    ]
